import logging
import re
from uuid import UUID

from supabase import Client

from app.core.config import get_settings
from app.db.supabase import get_supabase_client
from app.models.job import Job, JobKind, JobStatus
from app.schemas.job import CreateJobRequest, CreateJobResponse, JobStatusResponse
from app.schemas.attendance import CreateAttendanceJobResponse
from app.services.queue_service import QueueService, QueueServiceError

logger = logging.getLogger("uvicorn.error")

# Matches keys generated by StorageService: enrollments/{user_id}/{job_id}.{ext}
_ENROLLMENT_KEY_RE = re.compile(
    r"^enrollments/[a-f0-9\-]+/[a-f0-9\-]+\.\w+$"
)


class JobServiceError(Exception):
    pass


class CreateJobError(JobServiceError):
    pass


class JobNotFoundError(JobServiceError):
    pass


class JobNotPendingError(JobServiceError):
    """Raised when a job is not in PENDING status."""

    pass


class JobOwnershipError(JobServiceError):
    """Raised when a job does not belong to the authenticated user."""

    pass


class JobService:
    """Handles creation and querying of async processing jobs."""

    def __init__(self, client: Client | None = None, queue_service: QueueService | None = None):
        self.client = client or get_supabase_client()
        self.queue_service = queue_service or QueueService()

    async def create_enrollment_job(
        self, request: CreateJobRequest, user_id: str
    ) -> CreateJobResponse:
        """Create an enrollment job and enqueue it for async processing.

        1. Insert a PENDING row into the jobs table.
        2. Send a message to the enrollment SQS queue.
        3. Return the job_id.

        If the SQS send fails, the jobs row is rolled back (deleted).

        Args:
            request: The job creation request (kind, bucket, key).
            user_id: The authenticated student's user ID.

        Returns:
            CreateJobResponse containing the job_id.

        Raises:
            CreateJobError: If the job could not be created.
        """
        job_id = None
        try:
            # Validate bucket matches the configured enrollment bucket
            settings = get_settings()
            if request.bucket != settings.s3_enrollment_bucket:
                raise CreateJobError(
                    f"Invalid bucket: expected '{settings.s3_enrollment_bucket}'"
                )

            # Validate key matches the expected pattern and belongs to the user
            if not _ENROLLMENT_KEY_RE.match(request.key):
                raise CreateJobError(
                    "Invalid key format: must match enrollments/<user_id>/<job_id>.<ext>"
                )
            if not request.key.startswith(f"enrollments/{user_id}/"):
                raise CreateJobError("Key does not belong to the authenticated user")

            # Step 1: Insert job row
            result = (
                self.client.table("jobs")
                .insert(
                    {
                        "kind": JobKind.ENROLLMENT,
                        "status": JobStatus.PENDING,
                        "owner_user_id": user_id,
                        "s3_bucket": request.bucket,
                        "s3_key": request.key,
                    }
                )
                .execute()
            )

            job_id = result.data[0]["id"]

            # Step 2: Send SQS message
            self.queue_service.send_message(
                queue_url=settings.sqs_enrollment_queue_url,
                message_body={
                    "job_id": job_id,
                    "user_id": user_id,
                    "bucket": request.bucket,
                    "key": request.key,
                },
            )

            # Step 3: Return job_id
            return CreateJobResponse(job_id=job_id)

        except QueueServiceError as e:
            # SQS failed — rollback the jobs row
            if job_id:
                self.rollback_job(job_id)
            raise CreateJobError(f"Failed to enqueue job: {str(e)}") from e
        except CreateJobError:
            raise
        except Exception as e:
            if job_id:
                self.rollback_job(job_id)
            raise CreateJobError(f"Failed to create job: {str(e)}") from e

    async def get_job_status(
        self, job_id: UUID, owner_user_id: UUID
    ) -> JobStatusResponse:
        """Get the status of a job owned by the given user.

        Queries by both job ID and owner to enforce access control at
        the data layer — a missing row is indistinguishable from an
        unauthorized read.

        Args:
            job_id: The job's UUID.
            owner_user_id: The authenticated user's UUID.

        Returns:
            JobStatusResponse with current status, kind, error_message, and updated_at.

        Raises:
            JobNotFoundError: If the job does not exist or does not belong to the user.
        """
        try:
            result = (
                self.client.table("jobs")
                .select("id, kind, status, error_message, updated_at")
                .eq("id", str(job_id))
                .eq("owner_user_id", str(owner_user_id))
                .single()
                .execute()
            )
        except Exception as e:
            raise JobNotFoundError(f"Job {job_id} not found") from e

        if not result.data:
            raise JobNotFoundError(f"Job {job_id} not found")

        row = result.data
        return JobStatusResponse(
            job_id=row["id"],
            status=row["status"],
            kind=row["kind"],
            error_message=row["error_message"],
            updated_at=row["updated_at"],
        )

    def rollback_job(self, job_id: str) -> None:
        """Delete a jobs row on failure. Best-effort; errors are logged but not raised."""
        try:
            self.client.table("jobs").delete().eq("id", job_id).execute()
        except Exception:
            logger.exception("Failed to rollback job row %s", job_id)

    def get_enrollment_job_status(self, job_id: str, owner_user_id: str) -> dict:
        """Get the status of an enrollment job.

        Args:
            job_id: The job's UUID as a string.
            owner_user_id: The owner's user ID.

        Returns:
            Dict with id, kind, status, error_message, and updated_at.

        Raises:
            JobNotFoundError: If the job does not exist or does not belong to the user.
        """
        try:
            result = (
                self.client.table("jobs")
                .select("id, kind, status, error_message, updated_at")
                .eq("id", job_id)
                .eq("owner_user_id", owner_user_id)
                .single()
                .execute()
            )
        except Exception as e:
            raise JobNotFoundError(f"Enrollment job {job_id} not found") from e

        if not result.data:
            raise JobNotFoundError(f"Enrollment job {job_id} not found")

        return result.data

    def create_pending_enrollment_job(
        self, job_id: str, user_id: str, bucket: str, key: str
    ) -> dict:
        """Create a PENDING enrollment job in the database.

        Args:
            job_id: The UUID for the new job.
            user_id: The owner's user ID.
            bucket: S3 bucket where the photo will be uploaded.
            key: S3 object key for the photo.

        Returns:
            The created job row data.

        Raises:
            CreateJobError: If the job could not be created.
        """
        try:
            result = (
                self.client.table("jobs")
                .insert(
                    {
                        "id": job_id,
                        "kind": "ENROLLMENT",
                        "status": "PENDING",
                        "owner_user_id": user_id,
                        "s3_bucket": bucket,
                        "s3_key": key,
                    }
                )
                .execute()
            )
            if not result.data:
                raise CreateJobError("Failed to create enrollment job")
            return result.data[0]
        except CreateJobError:
            raise
        except Exception as e:
            raise CreateJobError(f"Failed to create enrollment job: {str(e)}") from e

    async def enqueue_enrollment_job(self, job_id: str, user_id: str) -> CreateJobResponse:
        """Enqueue an existing PENDING enrollment job.

        This retrieves the job details from the database and sends an SQS message
        to trigger async processing.

        Args:
            job_id: The job ID to enqueue (must exist and be PENDING).
            user_id: The ID of the job owner (for validation).

        Returns:
            CreateJobResponse containing the job_id.

        Raises:
            CreateJobError: If the job doesn't exist, is not PENDING, or SQS fails.
        """
        try:
            settings = get_settings()
            
            # Retrieve the job
            result = (
                self.client.table("jobs")
                .select("*")
                .eq("id", job_id)
                .single()
                .execute()
            )
            
            if not result.data:
                raise CreateJobError(f"Job {job_id} not found")
            
            job = result.data
            if job.get("status") != "PENDING":
                raise CreateJobError(
                    f"Job is not in PENDING status (current: {job.get('status')})"
                )
            
            if job.get("owner_user_id") != user_id:
                raise CreateJobError("Job does not belong to the authenticated user")
            
            # Send SQS message
            self.queue_service.send_message(
                queue_url=settings.sqs_enrollment_queue_url,
                message_body={
                    "job_id": job_id,
                    "user_id": user_id,
                    "s3_bucket": job.get("s3_bucket"),
                    "s3_key": job.get("s3_key"),
                },
            )
            
            return CreateJobResponse(job_id=job_id)
            
        except QueueServiceError as e:
            raise CreateJobError(f"Failed to enqueue job: {str(e)}") from e
        except CreateJobError:
            raise
        except Exception as e:
            raise CreateJobError(f"Failed to enqueue job: {str(e)}") from e

    def create_pending_attendance_job(
        self, job_id: str, user_id: str, bucket: str, key: str
    ) -> dict:
        """Create a PENDING attendance job in the database.

        Args:
            job_id: The UUID for the new job.
            user_id: The owner's user ID.
            bucket: S3 bucket where the photo will be uploaded.
            key: S3 object key for the photo.

        Returns:
            The created job row data.

        Raises:
            CreateJobError: If the job could not be created.
        """
        try:
            result = (
                self.client.table("jobs")
                .insert(
                    {
                        "id": job_id,
                        "kind": JobKind.ATTENDANCE,
                        "status": JobStatus.PENDING,
                        "owner_user_id": user_id,
                        "s3_bucket": bucket,
                        "s3_key": key,
                    }
                )
                .execute()
            )
            if not result.data:
                raise CreateJobError("Failed to create attendance job")
            return result.data[0]
        except CreateJobError:
            raise
        except Exception as e:
            raise CreateJobError(f"Failed to create attendance job: {str(e)}") from e

    def enqueue_attendance_job(
        self, job_id: str, user_id: str, class_id: str, session_id: str
    ) -> CreateAttendanceJobResponse:
        """Enqueue an existing PENDING attendance job.

        Validates ownership and PENDING status, transitions the job to
        QUEUED, and sends an SQS message to the attendance queue.

        Args:
            job_id: The job ID to enqueue (must exist and be PENDING).
            user_id: The ID of the job owner (for validation).
            class_id: The class associated with this attendance session.
            session_id: The attendance session ID linked to this job.

        Returns:
            CreateAttendanceJobResponse with job_id and session_id.

        Raises:
            JobNotFoundError: If the job doesn't exist.
            JobNotPendingError: If the job is not in PENDING status.
            JobOwnershipError: If the job doesn't belong to the user.
            CreateJobError: If SQS send or other operations fail.
        """
        try:
            settings = get_settings()

            # Retrieve the job
            try:
                result = (
                    self.client.table("jobs")
                    .select("*")
                    .eq("id", job_id)
                    .single()
                    .execute()
                )
            except Exception as e:
                raise JobNotFoundError(f"Job {job_id} not found") from e

            job = result.data
            if job.get("status") != "PENDING":
                raise JobNotPendingError(
                    f"Job is not in PENDING status (current: {job.get('status')})"
                )

            if job.get("owner_user_id") != user_id:
                raise JobOwnershipError("Job does not belong to the authenticated user")

            # Send SQS message
            self.queue_service.send_message(
                queue_url=settings.sqs_attendance_queue_url,
                message_body={
                    "job_id": job_id,
                    "user_id": user_id,
                    "class_id": class_id,
                    "s3_bucket": job.get("s3_bucket"),
                    "s3_key": job.get("s3_key"),
                },
            )

            # Transition job status to QUEUED after successful SQS send
            try:
                self.client.table("jobs").update(
                    {"status": JobStatus.QUEUED}
                ).eq("id", job_id).execute()
            except Exception:
                logger.exception("Failed to update job %s status to QUEUED", job_id)

            return CreateAttendanceJobResponse(
                job_id=job_id, session_id=session_id
            )

        except (JobNotFoundError, JobNotPendingError, JobOwnershipError):
            raise
        except QueueServiceError as e:
            raise CreateJobError(f"Failed to enqueue job: {str(e)}") from e
        except CreateJobError:
            raise
        except Exception as e:
            raise CreateJobError(f"Failed to enqueue job: {str(e)}") from e
