import logging
import re

from supabase import Client

from app.core.config import get_settings
from app.db.supabase import get_supabase_client
from app.schemas.job import CreateJobRequest, CreateJobResponse
from app.services.queue_service import QueueService, QueueServiceError

logger = logging.getLogger("uvicorn.error")

# Matches keys generated by StorageService: enrollment-photos/{user_id}/{uuid}.{ext}
_ENROLLMENT_KEY_RE = re.compile(
    r"^enrollment-photos/[a-f0-9\-]+/[a-f0-9\-]+\.\w+$"
)


class JobServiceError(Exception):
    pass


class CreateJobError(JobServiceError):
    pass


class JobService:
    """Handles creation of async processing jobs."""

    def __init__(self, client: Client | None = None, queue_service: QueueService | None = None):
        self.client = client or get_supabase_client()
        self.queue_service = queue_service or QueueService()

    async def create_enrollment_job(
        self, request: CreateJobRequest, user_id: str
    ) -> CreateJobResponse:
        """Create an enrollment job and enqueue it for async processing.

        1. Insert a PENDING row into the jobs table.
        2. Send a message to the enrollment SQS queue.
        3. Return the job_id.

        If the SQS send fails, the jobs row is rolled back (deleted).

        Args:
            request: The job creation request (kind, bucket, key).
            user_id: The authenticated student's user ID.

        Returns:
            CreateJobResponse containing the job_id.

        Raises:
            CreateJobError: If the job could not be created.
        """
        job_id = None
        try:
            # Validate bucket matches the configured enrollment bucket
            settings = get_settings()
            if request.bucket != settings.s3_enrollment_bucket:
                raise CreateJobError(
                    f"Invalid bucket: expected '{settings.s3_enrollment_bucket}'"
                )

            # Validate key matches the expected pattern and belongs to the user
            if not _ENROLLMENT_KEY_RE.match(request.key):
                raise CreateJobError(
                    "Invalid key format: must match enrollment-photos/<user_id>/<uuid>.<ext>"
                )
            if not request.key.startswith(f"enrollment-photos/{user_id}/"):
                raise CreateJobError("Key does not belong to the authenticated user")

            # Step 1: Insert job row
            result = (
                self.client.table("jobs")
                .insert(
                    {
                        "kind": request.kind,
                        "status": "PENDING",
                        "owner_user_id": user_id,
                        "s3_bucket": request.bucket,
                        "s3_key": request.key,
                    }
                )
                .execute()
            )

            job_id = result.data[0]["id"]

            # Step 2: Send SQS message
            self.queue_service.send_message(
                queue_url=settings.sqs_enrollment_queue_url,
                message_body={
                    "job_id": job_id,
                    "user_id": user_id,
                    "bucket": request.bucket,
                    "key": request.key,
                },
            )

            # Step 3: Return job_id
            return CreateJobResponse(job_id=job_id)

        except QueueServiceError as e:
            # SQS failed — rollback the jobs row
            if job_id:
                self._rollback_job(job_id)
            raise CreateJobError(f"Failed to enqueue job: {str(e)}") from e
        except CreateJobError:
            raise
        except Exception as e:
            if job_id:
                self._rollback_job(job_id)
            raise CreateJobError(f"Failed to create job: {str(e)}") from e

    def _rollback_job(self, job_id: str) -> None:
        """Delete a jobs row on failure. Best-effort; errors are logged but not raised."""
        try:
            self.client.table("jobs").delete().eq("id", job_id).execute()
        except Exception:
            logger.exception("Failed to rollback job row %s", job_id)
